apiVersion: v1
kind: Service
metadata:
  name: url-shortener-api-service
spec:
  type: LoadBalancer
  selector:
    app: url-shortener-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
